import { PlaceDetails, PlaceFormValues, PlaceType } from "@/types/place";

/**
 * Merges consecutive 1-hour time slots into consolidated ranges.
 * For example: [10, 11] (10 AM-11 AM, 11 AM-12 PM) -> "10 AM - 12 PM"
 */
export function mergeTimeSlots(selectedSlots: number[]): string {
  if (!selectedSlots || selectedSlots.length === 0) return "";

  const sorted = [...selectedSlots].sort((a, b) => a - b);

  const ranges: { start: number; end: number }[] = [];
  let currentRange = { start: sorted[0], end: sorted[0] };

  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === currentRange.end + 1) {
      currentRange.end = sorted[i];
    } else {
      ranges.push(currentRange);
      currentRange = { start: sorted[i], end: sorted[i] };
    }
  }
  ranges.push(currentRange);

  const formatHour = (h: number): string => {
    const ampm = h >= 12 && h < 24 ? "PM" : "AM";
    let displayHour = h % 12;
    if (displayHour === 0) displayHour = 12;
    return `${displayHour} ${ampm}`;
  };

  const formattedRanges = ranges.map((r) => {
    const startStr = formatHour(r.start);
    const endStr = formatHour(r.end + 1);
    return `${startStr} - ${endStr}`;
  });

  return formattedRanges.join(", ");
}

/**
 * Calculates continuous block durations to check if any exceeds 4 hours.
 */
export function getContinuousDurations(selectedSlots: number[]): number[] {
  if (!selectedSlots || selectedSlots.length === 0) return [];
  const sorted = [...selectedSlots].sort((a, b) => a - b);
  const durations: number[] = [];
  let currentLength = 1;

  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === sorted[i - 1] + 1) {
      currentLength++;
    } else {
      durations.push(currentLength);
      currentLength = 1;
    }
  }
  durations.push(currentLength);
  return durations;
}

/**
 * Normalizes raw form values into a complete PlaceDetails object.
 */
export function normalizePlaceDetails(formValues: PlaceFormValues): PlaceDetails {
  let normalizedCategories = Array.from(
    new Set(
      (formValues.categories || [])
        .map((cat) => cat.trim())
        .filter((cat) => cat.length > 0)
    )
  );

  if (normalizedCategories.includes("Free") && normalizedCategories.includes("Paid")) {
    normalizedCategories = normalizedCategories.filter((cat) => cat !== "Paid");
  }

  const normalizedImages = Array.from(
    new Set(
      (formValues.images || [])
        .map((img) => img.trim())
        .filter((img) => img.length > 0)
    )
  );

  const trimmedFee = (formValues.entryFee || "").trim();
  let feeValue = "";
  if (!trimmedFee) {
    feeValue =
      formValues.ticketRequired === "Yes"
        ? "FREE - TICKET REQUIRED"
        : "FREE - NO TICKET REQUIRED";
  } else {
    feeValue = trimmedFee;
  }

  const DAY_MAP: Record<string, string> = {
    Monday: "Mon",
    Tuesday: "Tue",
    Wednesday: "Wed",
    Thursday: "Thu",
    Friday: "Fri",
    Saturday: "Sat",
    Sunday: "Sun",
  };

  const closedOnStr = formValues.closedDays?.includes("Never Closed")
    ? "Never Closed"
    : (formValues.closedDays || [])
        .map((d) => DAY_MAP[d] || d)
        .join(",")
        .slice(0, 12);

  const now = new Date().toISOString();

  return {
    id: "", // Generated by backend

    placeName: formValues.placeName.trim(),
    description: formValues.description.trim(),

    placeType: (formValues.placeType || "Spot") as PlaceType,
    mainCategory: formValues.mainCategory.trim(),
    categories: normalizedCategories,
    images: normalizedImages,

    city: formValues.city.trim(),
    area: formValues.area.trim(),
    state: formValues.state.trim(),

    latitude: formValues.latitude.trim(),
    longitude: formValues.longitude.trim(),

    bestTimings: mergeTimeSlots(formValues.bestTimings || []),
    closedOn: closedOnStr,
    nearestMetro: formValues.nearestMetro.trim(),
    crowdLevel: formValues.crowdLevel.trim(),
    safetyNote: formValues.safetyNote.trim(),
    entryFee: feeValue,

    likes: "0",
    saves: "0",
    visited: "0",

    uploaderId: "",
    uploaderBadge: "Founder",
    createdAt: now,
    updatedAt: now,
  };
}

function parseHour(hStr: string): number {
  hStr = hStr.trim();
  const match = hStr.match(/^(\d+)\s*(AM|PM)$/i);
  if (!match) return 0;
  let h = parseInt(match[1]);
  const ampm = match[2].toUpperCase();
  if (ampm === "PM" && h !== 12) h += 12;
  if (ampm === "AM" && h === 12) h = 0;
  return h;
}

export function parseTimeSlots(timingsStr: string): number[] {
  if (!timingsStr) return [];
  const slots: number[] = [];
  const ranges = timingsStr.split(",");
  for (const range of ranges) {
    const parts = range.split("-");
    if (parts.length !== 2) continue;
    const start = parseHour(parts[0]);
    let end = parseHour(parts[1]);
    if (end === 0 && parts[1].toUpperCase().includes("AM")) {
      end = 24;
    }
    if (start < end) {
      for (let h = start; h < end; h++) {
        slots.push(h);
      }
    } else {
      for (let h = start; h < 24; h++) {
        slots.push(h);
      }
      for (let h = end; h < end; h++) {
        slots.push(h);
      }
    }
  }
  return Array.from(new Set(slots)).sort((a, b) => a - b);
}

export function mapPlaceDetailsToFormValues(place: PlaceDetails): PlaceFormValues {
  const feeVal = place.entryFee || "";

  let entryFee = "";
  let ticketRequired: "Yes" | "No" | "" = "";
  if (feeVal === "FREE - TICKET REQUIRED") {
    entryFee = "";
    ticketRequired = "Yes";
  } else if (feeVal === "FREE - NO TICKET REQUIRED") {
    entryFee = "";
    ticketRequired = "No";
  } else {
    entryFee = feeVal;
    ticketRequired = place.categories.includes("Free") ? "No" : "Yes";
  }

  const bestTimings = parseTimeSlots(place.bestTimings);
  const closedDays =
    (place.closedOn === "Never Closed"
      ? ["Never Closed"]
      : (place.closedOn || "")
          .split(",")
          .map((d) => d.trim())
          .filter(Boolean)) as PlaceFormValues["closedDays"];

  return {
    placeName: place.placeName || "",
    description: place.description || "",
    placeType: place.placeType || "Spot",
    mainCategory: place.mainCategory || "",
    categories: place.categories || [],
    images: place.images || [],
    city: place.city || "",
    area: place.area || "",
    state: place.state || "",
    latitude: place.latitude || "",
    longitude: place.longitude || "",
    bestTimings,
    closedDays,
    nearestMetro: place.nearestMetro || "",
    crowdLevel: (place.crowdLevel as PlaceFormValues["crowdLevel"]) || "",
    safetyNote: place.safetyNote || "",
    entryFee,
    ticketRequired,
  };
}
